django4/src/blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns=[
    #뷰클래스를 url 등록시, 뷰클래스.as_view()함수로 등록함
    path('', Index.as_view(), name='index'),
    #DetailView를 상속받은 클래스뷰는 pk매개변수에 id변수값을 넘겨줘야함
    path('<int:pk>/', Detail.as_view(),name='detail'),
    path('posting/', Posting.as_view(), name='posting'),
    path('search/', PostSearch.as_view(), name='postsearch'),
    ]

django4/src/django4/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import *
#기본 도메인이 웹서버가 실행되는 환경에 맞춰짐
#개발 과정에서의 기본 도메인 주소는 : 127.0.0.1:8000/
'''
urls.py : 만들어진 뷰 함수/ 클래스를 URL에 등록하는 공간
path(요청할 URL주소, 호출된 함수/클래스)
urlpatterns : 처리할 수 있는 URL-뷰를 저장하는 변수
'''
urlpatterns = [
    path('admin/', admin.site.urls),
    #http://127.0.0.1:8000/ 입력시, main 뷰함수가 호출됨
    path('', main),
    #http://127.0.0.1:8000/booklist 입력시, booklist 뷰함수가 호출됨
    path('booklist/', booklist),
    #127.0.0.1:8000/숫자값/ 입력시, getBook 뷰함수가 호출됨
    #book_id에 숫자값이 저장됨. 숫자를 넣는 공간에 문자를 넣으면 함수호출이 안됨
    path('<int:book_id>/', getBook),
    #127.0.0.1:8000/vote/로 시작하는 모든 요청들을,
    #vote폴더의 urls.py에서 관리하도록 등록하는 과정
    path('vote/', include('vote.urls')),
    #customlogin폴더에 있는 urls.py
    path('login/', include('customlogin.urls')),
    #social_django폴더 안에 있는 urls.py
    #다른 개발자가 만든 어플리케이션의 urls.py를 등록하고 사용할때,
    #app_name 변수에 어떤 값이 있는지 확인하지 않고 새로운 그룹명을 지정할 수 있음
    #-> include함수의 namespace 매개변수에 원하는 그룹명 지정 
    path('social/', include('social_django.urls', namespace='social')),
    
    #
    path('blog/', include('blog.urls')),
]
#사용자가 이미지, 첨부파일 요청 URL을 사용하면,
#서버의 하드디스크에 파일을 HTTP로 넘겨줄 수 있도록 등록하는 작업
from django.conf import settings #settings.py 임포트
from django.conf.urls.static import static #URL과 폴더경로를 등록하는 함수

#path 함수대신 static함수를 사용함
#127.0.0.1:8000/files/ 로 시작하는 요청은 프로젝트폴터/files/에서 파일을 꺼내도록 URL등록
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

django4/src/blog/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey

# Create your models here.


#카테고리
#카테고리명
class Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name








#글
#카테고리-외래키, 제목, 글쓴이-외래키, 글내용, 작성일
class Post(models.Model):
    c = models.ForeignKey(Category, on_delete=PROTECT)
    title = models.CharField(max_length=200)
    u=models.ForeignKey(User, on_delete=PROTECT)
    #TextField: 글자수제한이 없는 저장공간을 설정하는 클래스
    #null: 데이터베이스에 해당변수값이 없어도 저장되도록 설정하는 매개변수
    #blank: 사용자가 입력양식에 해당변수값을 빈칸으로 둬도 폼을 서버에 전달할 수 있도록 설정하는 매개변수
    # 설정하는 매개변수. null과 blank매개변수는 모든 Field클래스에서 사용할 수 있음
    content = models.TextField(null=True,blank=True)
    #auto_now_add(DateTimeField나 DateField에서 사용가능)
    #: 객체 생성시, 서버 기준의 날짜/시간이 자동으로 입력되도록 설정하는 매개변수
    
    pub_date = models.DateTimeField(auto_now_add=True)
    




#글의 첨부파일
#글-외래키, 파일저장공간
class PostFile(models.Model):
    p = models.ForeignKey(Post,on_delete=CASCADE)
    #FileField : 모든 파일을 서버 하드디스크에 저장하는 공간
    #upload_to : 객체 생성 중 FileField에 저장한 파일이 실제로 저장되는 경로
    f = models.FileField(upload_to='files/')

#글의 이미지파일
#글-외래키, 이미지파일저장공간
class PostImage(models.Model):
    p = models.ForeignKey(Post, on_delete=CASCADE)
    #ImageField : 이미지파일을 서버하드디스크에 저장하는 클래스
    #단, 해당 필드를 사용하려면 Pillow 모듈이 파이썬에 설치가 되있어야함
    #Pillow : python에서 이미지처리에 사용되는 대표적인 라이브러리
    i = models.ImageField(upload_to='images/')

django4/src/blog/forms.py
'''
Created on 2019. 5. 4.

@author: 평일오후
'''
from django import forms
from blog.models import Post
#글쓰기에 사용할 폼클래스 - Post모델클래스와 연동
#Post 모델클래스에 변수 외에 PostImage, PostFile 객체 생성에 사용할 첨부파일입력공간생성
class PostingForm(forms.ModelForm):
    #required: 사용자가 반드시 입력해야하는 입력 양식을 설정할 때 사용하는 매개변수
    #required에 기본값을 True. True인 경우 사용자가 반드시 값을 입력해야함
    #False인 경우 사용자가 해당 입력공간을 입력하지 않아도 됨
    #ClearableFileInput : HTML코드 기준 <input type=File>인 입력공간에 
    #별도의 속성을 설정할 때 사용하는 위젯
    files = forms.FileField(label='첨부파일',required=False, widget=forms.ClearableFileInput(attrs={'multiple':True}))
    images = forms.ImageField(label='이미지',required=False, widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = Post
        fields = ['c', 'title', 'content']
        #exclude = ['u', 'pub_date']

django4/src/blog/views.py
from django.shortcuts import render

# Create your views here.
'''
클래스 기반의 뷰를 만들때, 장고에서 만든 뷰에 기능을 다루는 클래스를 상속해야함
- 제네릭뷰 : 장고에서 제공하는 여러가지 상황별 뷰 기능을 구현한 클래스
ex)모델클래스 객체 목록, 모델클래스의 특정객체를 출력기능, 폼클래스 클래스를 활용하는 기능
'''
from django.views.generic.list import ListView
from blog.models import Post, PostFile, PostImage
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import PostingForm
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
#글 목록
'''
ListView : 특정 모델클래스의 객체 목록을 다루는 기능이 구현된 뷰
대표적인 설정할 수 있는 변수
template_name : 사용할 HTML 파일 경로
model : 연동할 모델클래스
context_object_name: 객체 리스트를 HTMl에서 받을 때 사용할 변수이름
paginate_by: 한 페이지에 몇 개의 객체를 출력할지 설정하는 변수
'''
class Index(ListView):
    template_name = 'blog/index.html' #render 2번째
    model = Post
    context_object_name = 'objs'    #render 3번째
    paginate_by = 5
#글 상세보기
'''
DetailView : 데이터베이스에 특정 모델 클래스에서 한 개의 객체를 추출하는 제네릭뷰
단, 해당 뷰 클래스를 등록할 때, pk 매개변수에 id변수값을 넘겨주도록 URL등록을 해야함
template_name, model, context_object_name (공통)

'''
class Detail(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'p'
#글쓰기
'''
FormView: 폼클래스를 기반으로 사용자에게 입력공간을 제공(GET방식)하고,
사용자가 입력한 데이터를 바탕으로 객체를 생성(POST방식)을 처리해주는 제네릭뷰
template_name , context_object_name (공통)
form_class : 연동할 폼클래스를 저장하는 변수

Posting에서는 Post객체 뿐 아니라 사용자가 보낸 파일 정보를 바탕으로 PostImage,PostFile
객체도 생성해야되기 때문에 POST방식 요청에 대한 함수를 오버라이딩해서 기능을 바꿔야함 

뷰함수의 데코레이터 기능을 뷰클래스는 XXXMixin 클래스를 상속하는 것으로 대체
데코레이터 함수인 login_required 대신 LoginRequiredMixin 클래스를 상속하는 것으로 대체
주의할 점, XXXMixin클래스 상속시, 제네릭뷰보다 먼저 상속해야함
'''
class Posting(LoginRequiredMixin, FormView):
    template_name = 'blog/posting.html'
    context_object_name = 'form'
    form_class = PostingForm
    #POST방식 요청에 대한 함수를 오버라이딩
    #사용자 입력이 유효한 경우 호출되는 함수 -> form_valid함수를 오버라이딩
    #form_valid의 form 매개변수: 사용자 입력을 기반으로 생성된 form_class객체
    def form_valid(self, form):
        #form 객체를 기반으로 Post 객체 생성
        p= form.save(commit=False)  #데이터베이스에는 저장x
        #->u 변수가 비어있기 때문에 데이터베이스에 저장할 수 없음
        #생성된 Post객체의 빈값 채우기(u변수)
        #뷰함수에서 클라이언트가 접속한 유저정보 : request.user에 저장됨
        #뷰클래스에서 request변수는 self.request로 꺼낼 수 있음
        #해당 요청을 보낸 클라이언트의 유저정보를 Post 객체의 u변수에 저장
        p.u = self.request.user
        #데이터베이스에 저장
        p.save()
        #사용자가 첨부한 파일/이미지 데이터마다 PostFile, PostImage객체를 생성
        #및 데이터베이스에 저장
        #사용자가 첨부한 파일정보는 request.FILES(사전형) 변수가 저장함
        #FILES에 데이터를 꺼낼 때 <input>태그의 name속성값으로 꺼낼 수 있음
        for f in self.request.FILES.getlist('files'):
            pf = PostFile()
            pf.p = p    #새로 생성된 Post객체를 대입
            pf.f = f    #첨부한 파일데이터를 파일필드에 대입
            pf.save()
            
        for f in self.request.FILES.getlist('images'):
            pf = PostImage()
            pf.p = p    #새로 생성된 Post객체를 대입
            pf.i = f    #첨부한 파일데이터를 파일필드에 대입
            pf.save()
        #생성된 글을 상세보기하는 URL을 리다이렉트
        return HttpResponseRedirect(reverse('blog:detail', args=(p.id,))) 
        
#검색
#특정 조건을 만족하는 Post 객체를 리스트로 추출 후 화면에 추력
class PostSearch(ListView):
    template_name = 'blog/postsearch.html'
    model = Post
    context_object_name = 'objs'
    
    #사용자가 입력한 검색어를 포함한 Post객체가 추출되도록 get_queryset함수를 오버라이드
    #get_queryset 함수 : 특정 모델클래스에서 객체를 꺼낼때 어떤 조건으로 꺼내야하는지 설정할 수 있는 함수.
    #기본값: 모든 객체를 추출하는 모델클래스.objects.all()함수로 설정
    def get_queryset(self):
        #사용자가 <form>으로 넘겨준 데이터 중 'search' 이름으로 날라온 데이터 추출
        #self.kwargs : GET이나 POST로 넘겨준 <form>태그의 추가 데이터
        print('사용자가 넘겨준 데이터:', self.request.GET)
        '''s=self.kwargs['search']는 오류발생가능 '''
        #'search' key로 데이터를 추출하되, 해당 key로 데이터가 존재하지 않으면
        #빈 문자열을 반환하도록 설정. 사전형 데이터에서 사용할 수 있는 get함수
        s=self.request.GET.get('search', '') 
        #추출한 데이터가 빈 문자열인지 확인
        if s:
            #빈 문자열이 아닌 경우 Post.objects.filter()함수를 사용해서 검색어에 맞는 객체들을 추출
            #filter(변수__조건 = 값) : 모델클래스 객체들이 특정 변수에 특정 조건을 만족하는지 확인해 만족하는 객체들을 리스트형태로 반환하는 함수
            #조건에 들어가는 명령어는 django라이브러리에서 지정함
            #icontains : 특정 변수에 우변에 값이 포함되어있으면 객체를 추출하도록 설정하는 조건
            #사용자가 입력한 키워드 (s 변수)를 제목에 포함하는 Post객체들을 추출
            objs = Post.objects.filter(title__icontains = s)
        else: # 사용자가 키워드를 입력하지 않은 경우의 처리
            objs = Post.objects.all()
        #추출한 데이터를 return으로 반환
        return objs

django4/src/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
{# p :Post 객체 #}
<h3>[ {{ p.c}} ] {{ p.title }}]</h3>
<p> {{ p.u }} / {{ p.pub_date}} </p>
<pre>{{p.content }}</pre>
<!-- 첨부파일 링크 -->
{% for f in p.postfile_set.all %}
	{#글에 연동된 첨부파일을 다운 받을수 있는 링크 제공#}
	{#파일필드.url : 파일을 다운받을 수 있는 URL주소를 저장한 변수#}
	{#파일필드.name : 실제 파일의 이름#}
	<a download href="{{f.f.url}}"> {{f.f.name}}</a>
	<br>
{% endfor %}
<!-- 첨부했던 이미지 로드 -->
{% for f in p.postimage_set.all %}
	{#글에 연동된 첨부파일을 다운 받을수 있는 링크 제공#}
	{#파일필드.url : 파일을 다운받을 수 있는 URL주소를 저장한 변수#}
	{#파일필드.name : 실제 파일의 이름#}
	<img src="{{f.i.url}}" width="40%"><br>
{% endfor %}
<a href = " {% url 'blog:index' %}">메인페이지로 돌아가기</a>
{% endblock %}

django4/src/blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
{# objs :Post 객체 리스트 page_obj : ListView가 넘겨주는 추가 변수.페이지정보를 전달하는 변수 #}
<!-- 이전페이지 버튼 -->
{% if page_obj.has_previous %}
	{# page_obj.has_previous() : 현재 페이지를 기준으로 이전페이지가 존재하는지 확인 #}
	{# page_obj.previous_page_number : 현재 페이지를 기준으로 이전페이지 번호가 저장된 변수 #}
	<a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>
{% else %}
	<a>이전페이지</a>
{% endif %}
<!-- 다음페이지 버튼 -->
{% if page_obj.has_next %}
	{# page_obj.has_next() : 현재 페이지를 기준으로 이전페이지가 존재하는지 확인 #}
	{# page_obj.next_page_number : 현재 페이지를 기준으로 이전페이지 번호가 저장된 변수 #}
	<a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
{% else %}
	<a>다음페이지</a>
{% endif %}
<!-- 테이블 - 게시물 출력 -->
<table width="90%">
	<tr>
		<th>글번호</th>
		<th>카테고리</th>
		<th>제목</th>
		<th>작성자</th>
		<th>작성일</th>
	</tr>
	{% for obj in objs%}
		<tr>
			<th>{{obj.id}}</th>
			<th>{{obj.c}}</th>
			<th><a href=" {% url 'blog:detail' obj.id %}">{{obj.title}}</a></th>
			<th>{{obj.u}}</th>
			<th>{{obj.pub_date}}</th>
		</tr>
	{% endfor %}
</table>
<!-- 글쓰기 링크 -->
<a href="{% url 'blog:posting' %}">글쓰기</a>
<!-- 검색 기능 -->
<form action="{% url 'blog:postsearch' %}" method = 'get'>
	{% csrf_token %}
	<input type = "test" name="search">
	<input type = "submit" value="검색">
</form>
{% endblock %}

django4/src/blog/templates/blog/posting.html
{% extends 'base.html' %}
{% block content %}
<h3> 글쓰기 </h3>
<!-- form 태그의 enctype='multipart/form-data'
-> 해당 폼으로 파일데이터를 웹서버에 전달할 수 있도록 허용하는 속성
만약, 이 속성이 설정되지 않은 상태로 첨부파일을 보낼경우, request.FILES가 항상 None값을 가짐 -->
<form action = '' method = 'post' enctype = 'multipart/form-data'>
	{% csrf_token %}
	<table>
		{{form.as_table}}
	</table>
	<!-- 중 하나
	{{form.as_p}}
	<ul>
	{{form.as_ul}}
	</ul>
	 -->
	 <input type ='submit' value="글쓰기">
</form>

<a href= "{% url 'blog:index' %}">메인페이지로 돌아가기</a>
{% endblock %}

django4/src/blog/templates/blog/postsearch.html
{% extends 'base.html' %}
{% block content %}
{#objs : 검색결과를 만족하는 Post 객체 리스트#}
<!-- 검색 기능 -->
<form action="{% url 'blog:postsearch' %}" method = 'get'>
	{% csrf_token %}
	<input type = "test" name="search">
	<input type = "submit" value="검색">
</form>
{# objs 변수에 Post객체가 한개라도 있으면 True #}
{% if objs %}
<!-- 테이블 - 게시물 출력 -->
<table width="90%">
	<tr>
		<th>글번호</th>
		<th>카테고리</th>
		<th>제목</th>
		<th>작성자</th>
		<th>작성일</th>
	</tr>
	{% for obj in objs%}
		<tr>
			<th>{{obj.id}}</th>
			<th>{{obj.c}}</th>
			<th><a href=" {% url 'blog:detail' obj.id %}">{{obj.title}}</a></th>
			<th>{{obj.u}}</th>
			<th>{{obj.pub_date}}</th>
		</tr>
	{% endfor %}
</table>
{% else %}
	<p>검색결과가 없습니다</p>
{% endif %}


{% endblock %}